---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: aplicamos-crawl
  name: aplicamos-crawl
spec:
  progressDeadlineSeconds: 300
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        app: aplicamos-crawl
    spec:
      containers:
        - name: aplicamos-crawl
          image: aplicamos.azurecr.io/aplicamos-crawl:$TAG_NAME
          envFrom:
          - secretRef:
              name: aplicamos-crawl
          ports:
          - containerPort: 80
            protocol: TCP
          resources:
            requests:
              memory: "64M"
              cpu: "64m"
            limits:
              memory: "128M"
              cpu: "128m"
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 80
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 80
            initialDelaySeconds: 5
      imagePullSecrets:
      - name: registry
