---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: blacktrader-mm-rsi
spec:
  schedule: "0 10 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: blacktrader-mm-rsi
            image: brucorreia/blacktrader-mm-rsi:$TAG_NAME
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
